<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Canton;

class CantonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Canton::create(['id_provincia' => 1, 'name' => 'CUENCA']);
        Canton::create(['id_provincia' => 1, 'name' => 'GIRÓN']);
        Canton::create(['id_provincia' => 1, 'name' => 'GUALACEO']);
        Canton::create(['id_provincia' => 1, 'name' => 'NABÓN']);
        Canton::create(['id_provincia' => 1, 'name' => 'PAUTE']);
        Canton::create(['id_provincia' => 1, 'name' => 'PUCARA']);
        Canton::create(['id_provincia' => 1, 'name' => 'SAN FERNANDO']);
        Canton::create(['id_provincia' => 1, 'name' => 'SANTA ISABEL']);
        Canton::create(['id_provincia' => 1, 'name' => 'SIGSIG']);
        Canton::create(['id_provincia' => 1, 'name' => 'OÑA']);
        Canton::create(['id_provincia' => 1, 'name' => 'CHORDELEG']);
        Canton::create(['id_provincia' => 1, 'name' => 'EL PAN']);
        Canton::create(['id_provincia' => 1, 'name' => 'SEVILLA DE ORO']);
        Canton::create(['id_provincia' => 1, 'name' => 'GUACHAPALA']);
        Canton::create(['id_provincia' => 1, 'name' => 'CAMILO PONCE ENRÍQUEZ']);
        Canton::create(['id_provincia' => 2, 'name' => 'GUARANDA']);
        Canton::create(['id_provincia' => 2, 'name' => 'CHILLANES']);
        Canton::create(['id_provincia' => 2, 'name' => 'CHIMBO']);
        Canton::create(['id_provincia' => 2, 'name' => 'ECHEANDÍA']);
        Canton::create(['id_provincia' => 2, 'name' => 'SAN MIGUEL']);
        Canton::create(['id_provincia' => 2, 'name' => 'CALUMA']);
        Canton::create(['id_provincia' => 2, 'name' => 'LAS NAVES']);
        Canton::create(['id_provincia' => 3, 'name' => 'AZOGUES']);
        Canton::create(['id_provincia' => 3, 'name' => 'BIBLIÁN']);
        Canton::create(['id_provincia' => 3, 'name' => 'CAÑAR']);
        Canton::create(['id_provincia' => 3, 'name' => 'LA TRONCAL']);
        Canton::create(['id_provincia' => 3, 'name' => 'EL TAMBO']);
        Canton::create(['id_provincia' => 3, 'name' => 'DÉLEG']);
        Canton::create(['id_provincia' => 3, 'name' => 'SUSCAL']);
        Canton::create(['id_provincia' => 4, 'name' => 'TULCÁN']);
        Canton::create(['id_provincia' => 4, 'name' => 'BOLÍVAR']);
        Canton::create(['id_provincia' => 4, 'name' => 'ESPEJO']);
        Canton::create(['id_provincia' => 4, 'name' => 'MIRA']);
        Canton::create(['id_provincia' => 4, 'name' => 'MONTÚFAR']);
        Canton::create(['id_provincia' => 4, 'name' => 'SAN PEDRO DE HUACA']);
        Canton::create(['id_provincia' => 5, 'name' => 'LATACUNGA']);
        Canton::create(['id_provincia' => 5, 'name' => 'LA MANÁ']);
        Canton::create(['id_provincia' => 5, 'name' => 'PANGUA']);
        Canton::create(['id_provincia' => 5, 'name' => 'PUJILI']);
        Canton::create(['id_provincia' => 5, 'name' => 'SALCEDO']);
        Canton::create(['id_provincia' => 5, 'name' => 'SAQUISILÍ']);
        Canton::create(['id_provincia' => 5, 'name' => 'SIGCHOS']);
        Canton::create(['id_provincia' => 6, 'name' => 'RIOBAMBA']);
        Canton::create(['id_provincia' => 6, 'name' => 'ALAUSI']);
        Canton::create(['id_provincia' => 6, 'name' => 'COLTA']);
        Canton::create(['id_provincia' => 6, 'name' => 'CHAMBO']);
        Canton::create(['id_provincia' => 6, 'name' => 'CHUNCHI']);
        Canton::create(['id_provincia' => 6, 'name' => 'GUAMOTE']);
        Canton::create(['id_provincia' => 6, 'name' => 'GUANO']);
        Canton::create(['id_provincia' => 6, 'name' => 'PALLATANGA']);
        Canton::create(['id_provincia' => 6, 'name' => 'PENIPE']);
        Canton::create(['id_provincia' => 6, 'name' => 'CUMANDÁ']);
        Canton::create(['id_provincia' => 7, 'name' => 'MACHALA']);
        Canton::create(['id_provincia' => 7, 'name' => 'ARENILLAS']);
        Canton::create(['id_provincia' => 7, 'name' => 'ATAHUALPA']);
        Canton::create(['id_provincia' => 7, 'name' => 'BALSAS']);
        Canton::create(['id_provincia' => 7, 'name' => 'CHILLA']);
        Canton::create(['id_provincia' => 7, 'name' => 'EL GUABO']);
        Canton::create(['id_provincia' => 7, 'name' => 'HUAQUILLAS']);
        Canton::create(['id_provincia' => 7, 'name' => 'MARCABELÍ']);
        Canton::create(['id_provincia' => 7, 'name' => 'PASAJE']);
        Canton::create(['id_provincia' => 7, 'name' => 'PIÑAS']);
        Canton::create(['id_provincia' => 7, 'name' => 'PORTOVELO']);
        Canton::create(['id_provincia' => 7, 'name' => 'SANTA ROSA']);
        Canton::create(['id_provincia' => 7, 'name' => 'ZARUMA']);
        Canton::create(['id_provincia' => 7, 'name' => 'LAS LAJAS']);
        Canton::create(['id_provincia' => 8, 'name' => 'ESMERALDAS']);
        Canton::create(['id_provincia' => 8, 'name' => 'ELOY ALFARO']);
        Canton::create(['id_provincia' => 8, 'name' => 'MUISNE']);
        Canton::create(['id_provincia' => 8, 'name' => 'QUININDÉ']);
        Canton::create(['id_provincia' => 8, 'name' => 'SAN LORENZO']);
        Canton::create(['id_provincia' => 8, 'name' => 'ATACAMES']);
        Canton::create(['id_provincia' => 8, 'name' => 'RIOVERDE']);
        Canton::create(['id_provincia' => 8, 'name' => 'LA CONCORDIA']);
        Canton::create(['id_provincia' => 9, 'name' => 'GUAYAQUIL']);
        Canton::create(['id_provincia' => 9, 'name' => 'ALFREDO BAQUERIZO MORENO (JUJÁN)']);
        Canton::create(['id_provincia' => 9, 'name' => 'BALAO']);
        Canton::create(['id_provincia' => 9, 'name' => 'BALZAR']);
        Canton::create(['id_provincia' => 9, 'name' => 'COLIMES']);
        Canton::create(['id_provincia' => 9, 'name' => 'DAULE']);
        Canton::create(['id_provincia' => 9, 'name' => 'DURÁN']);
        Canton::create(['id_provincia' => 9, 'name' => 'EL EMPALME']);
        Canton::create(['id_provincia' => 9, 'name' => 'EL TRIUNFO']);
        Canton::create(['id_provincia' => 9, 'name' => 'MILAGRO']);
        Canton::create(['id_provincia' => 9, 'name' => 'NARANJAL']);
        Canton::create(['id_provincia' => 9, 'name' => 'NARANJITO']);
        Canton::create(['id_provincia' => 9, 'name' => 'PALESTINA']);
        Canton::create(['id_provincia' => 9, 'name' => 'PEDRO CARBO']);
        Canton::create(['id_provincia' => 9, 'name' => 'SAMBORONDÓN']);
        Canton::create(['id_provincia' => 9, 'name' => 'SANTA LUCÍA']);
        Canton::create(['id_provincia' => 9, 'name' => 'SALITRE (URBINA JADO)']);
        Canton::create(['id_provincia' => 9, 'name' => 'SAN JACINTO DE YAGUACHI']);
        Canton::create(['id_provincia' => 9, 'name' => 'PLAYAS']);
        Canton::create(['id_provincia' => 9, 'name' => 'SIMÓN BOLÍVAR']);
        Canton::create(['id_provincia' => 9, 'name' => 'CORONEL MARCELINO MARIDUEÑA']);
        Canton::create(['id_provincia' => 9, 'name' => 'LOMAS DE SARGENTILLO']);
        Canton::create(['id_provincia' => 9, 'name' => 'NOBOL']);
        Canton::create(['id_provincia' => 9, 'name' => 'GENERAL ANTONIO ELIZALDE']);
        Canton::create(['id_provincia' => 9, 'name' => 'ISIDRO AYORA']);
        Canton::create(['id_provincia' => 10, 'name' => 'IBARRA']);
        Canton::create(['id_provincia' => 10, 'name' => 'ANTONIO ANTE']);
        Canton::create(['id_provincia' => 10, 'name' => 'COTACACHI']);
        Canton::create(['id_provincia' => 10, 'name' => 'OTAVALO']);
        Canton::create(['id_provincia' => 10, 'name' => 'PIMAMPIRO']);
        Canton::create(['id_provincia' => 10, 'name' => 'SAN MIGUEL DE URCUQUÍ']);
        Canton::create(['id_provincia' => 11, 'name' => 'LOJA']);
        Canton::create(['id_provincia' => 11, 'name' => 'CALVAS']);
        Canton::create(['id_provincia' => 11, 'name' => 'CATAMAYO']);
        Canton::create(['id_provincia' => 11, 'name' => 'CELICA']);
        Canton::create(['id_provincia' => 11, 'name' => 'CHAGUARPAMBA']);
        Canton::create(['id_provincia' => 11, 'name' => 'ESPÍNDOLA']);
        Canton::create(['id_provincia' => 11, 'name' => 'GONZANAMÁ']);
        Canton::create(['id_provincia' => 11, 'name' => 'MACARÁ']);
        Canton::create(['id_provincia' => 11, 'name' => 'PALTAS']);
        Canton::create(['id_provincia' => 11, 'name' => 'PUYANGO']);
        Canton::create(['id_provincia' => 11, 'name' => 'SARAGURO']);
        Canton::create(['id_provincia' => 11, 'name' => 'SOZORANGA']);
        Canton::create(['id_provincia' => 11, 'name' => 'ZAPOTILLO']);
        Canton::create(['id_provincia' => 11, 'name' => 'PINDAL']);
        Canton::create(['id_provincia' => 11, 'name' => 'QUILANGA']);
        Canton::create(['id_provincia' => 11, 'name' => 'OLMEDO']);
        Canton::create(['id_provincia' => 12, 'name' => 'BABAHOYO']);
        Canton::create(['id_provincia' => 12, 'name' => 'BABA']);
        Canton::create(['id_provincia' => 12, 'name' => 'MONTALVO']);
        Canton::create(['id_provincia' => 12, 'name' => 'PUEBLOVIEJO']);
        Canton::create(['id_provincia' => 12, 'name' => 'QUEVEDO']);
        Canton::create(['id_provincia' => 12, 'name' => 'URDANETA']);
        Canton::create(['id_provincia' => 12, 'name' => 'VENTANAS']);
        Canton::create(['id_provincia' => 12, 'name' => 'VÍNCES']);
        Canton::create(['id_provincia' => 12, 'name' => 'PALENQUE']);
        Canton::create(['id_provincia' => 12, 'name' => 'BUENA FÉ']);
        Canton::create(['id_provincia' => 12, 'name' => 'VALENCIA']);
        Canton::create(['id_provincia' => 12, 'name' => 'MOCACHE']);
        Canton::create(['id_provincia' => 12, 'name' => 'QUINSALOMA']);
        Canton::create(['id_provincia' => 13, 'name' => 'PORTOVIEJO']);
        Canton::create(['id_provincia' => 13, 'name' => 'BOLÍVAR']);
        Canton::create(['id_provincia' => 13, 'name' => 'CHONE']);
        Canton::create(['id_provincia' => 13, 'name' => 'EL CARMEN']);
        Canton::create(['id_provincia' => 13, 'name' => 'FLAVIO ALFARO']);
        Canton::create(['id_provincia' => 13, 'name' => 'JIPIJAPA']);
        Canton::create(['id_provincia' => 13, 'name' => 'JUNÍN']);
        Canton::create(['id_provincia' => 13, 'name' => 'MANTA']);
        Canton::create(['id_provincia' => 13, 'name' => 'MONTECRISTI']);
        Canton::create(['id_provincia' => 13, 'name' => 'PAJÁN']);
        Canton::create(['id_provincia' => 13, 'name' => 'PICHINCHA']);
        Canton::create(['id_provincia' => 13, 'name' => 'ROCAFUERTE']);
        Canton::create(['id_provincia' => 13, 'name' => 'SANTA ANA']);
        Canton::create(['id_provincia' => 13, 'name' => 'SUCRE']);
        Canton::create(['id_provincia' => 13, 'name' => 'TOSAGUA']);
        Canton::create(['id_provincia' => 13, 'name' => '24 DE MAYO']);
        Canton::create(['id_provincia' => 13, 'name' => 'PEDERNALES']);
        Canton::create(['id_provincia' => 13, 'name' => 'OLMEDO']);
        Canton::create(['id_provincia' => 13, 'name' => 'PUERTO LÓPEZ']);
        Canton::create(['id_provincia' => 13, 'name' => 'JAMA']);
        Canton::create(['id_provincia' => 13, 'name' => 'JARAMIJÓ']);
        Canton::create(['id_provincia' => 13, 'name' => 'SAN VICENTE']);
        Canton::create(['id_provincia' => 14, 'name' => 'MORONA']);
        Canton::create(['id_provincia' => 14, 'name' => 'GUALAQUIZA']);
        Canton::create(['id_provincia' => 14, 'name' => 'LIMÓN INDANZA']);
        Canton::create(['id_provincia' => 14, 'name' => 'PALORA']);
        Canton::create(['id_provincia' => 14, 'name' => 'SANTIAGO']);
        Canton::create(['id_provincia' => 14, 'name' => 'SUCÚA']);
        Canton::create(['id_provincia' => 14, 'name' => 'HUAMBOYA']);
        Canton::create(['id_provincia' => 14, 'name' => 'SAN JUAN BOSCO']);
        Canton::create(['id_provincia' => 14, 'name' => 'TAISHA']);
        Canton::create(['id_provincia' => 14, 'name' => 'LOGROÑO']);
        Canton::create(['id_provincia' => 14, 'name' => 'PABLO SEXTO']);
        Canton::create(['id_provincia' => 14, 'name' => 'TIWINTZA']);
        Canton::create(['id_provincia' => 15, 'name' => 'TENA']);
        Canton::create(['id_provincia' => 15, 'name' => 'ARCHIDONA']);
        Canton::create(['id_provincia' => 15, 'name' => 'EL CHACO']);
        Canton::create(['id_provincia' => 15, 'name' => 'QUIJOS']);
        Canton::create(['id_provincia' => 15, 'name' => 'CARLOS JULIO AROSEMENA TOLA']);
        Canton::create(['id_provincia' => 16, 'name' => 'PASTAZA']);
        Canton::create(['id_provincia' => 16, 'name' => 'MERA']);
        Canton::create(['id_provincia' => 16, 'name' => 'SANTA CLARA']);
        Canton::create(['id_provincia' => 16, 'name' => 'ARAJUNO']);
        Canton::create(['id_provincia' => 17, 'name' => 'QUITO']);
        Canton::create(['id_provincia' => 17, 'name' => 'CAYAMBE']);
        Canton::create(['id_provincia' => 17, 'name' => 'MEJIA']);
        Canton::create(['id_provincia' => 17, 'name' => 'PEDRO MONCAYO']);
        Canton::create(['id_provincia' => 17, 'name' => 'RUMIÑAHUI']);
        Canton::create(['id_provincia' => 17, 'name' => 'SAN MIGUEL DE LOS BANCOS']);
        Canton::create(['id_provincia' => 17, 'name' => 'PEDRO VICENTE MALDONADO']);
        Canton::create(['id_provincia' => 17, 'name' => 'PUERTO QUITO']);
        Canton::create(['id_provincia' => 18, 'name' => 'AMBATO']);
        Canton::create(['id_provincia' => 18, 'name' => 'BAÑOS DE AGUA SANTA']);
        Canton::create(['id_provincia' => 18, 'name' => 'CEVALLOS']);
        Canton::create(['id_provincia' => 18, 'name' => 'MOCHA']);
        Canton::create(['id_provincia' => 18, 'name' => 'PATATE']);
        Canton::create(['id_provincia' => 18, 'name' => 'QUERO']);
        Canton::create(['id_provincia' => 18, 'name' => 'SAN PEDRO DE PELILEO']);
        Canton::create(['id_provincia' => 18, 'name' => 'SANTIAGO DE PÍLLARO']);
        Canton::create(['id_provincia' => 18, 'name' => 'TISALEO']);
        Canton::create(['id_provincia' => 19, 'name' => 'ZAMORA']);
        Canton::create(['id_provincia' => 19, 'name' => 'CHINCHIPE']);
        Canton::create(['id_provincia' => 19, 'name' => 'NANGARITZA']);
        Canton::create(['id_provincia' => 19, 'name' => 'YACUAMBI']);
        Canton::create(['id_provincia' => 19, 'name' => 'YANTZAZA (YANZATZA)']);
        Canton::create(['id_provincia' => 19, 'name' => 'EL PANGUI']);
        Canton::create(['id_provincia' => 19, 'name' => 'CENTINELA DEL CÓNDOR']);
        Canton::create(['id_provincia' => 19, 'name' => 'PALANDA']);
        Canton::create(['id_provincia' => 19, 'name' => 'PAQUISHA']);
        Canton::create(['id_provincia' => 20, 'name' => 'SAN CRISTÓBAL']);
        Canton::create(['id_provincia' => 20, 'name' => 'ISABELA']);
        Canton::create(['id_provincia' => 20, 'name' => 'SANTA CRUZ']);
        Canton::create(['id_provincia' => 21, 'name' => 'LAGO AGRIO']);
        Canton::create(['id_provincia' => 21, 'name' => 'GONZALO PIZARRO']);
        Canton::create(['id_provincia' => 21, 'name' => 'PUTUMAYO']);
        Canton::create(['id_provincia' => 21, 'name' => 'SHUSHUFINDI']);
        Canton::create(['id_provincia' => 21, 'name' => 'SUCUMBÍOS']);
        Canton::create(['id_provincia' => 21, 'name' => 'CASCALES']);
        Canton::create(['id_provincia' => 21, 'name' => 'CUYABENO']);
        Canton::create(['id_provincia' => 22, 'name' => 'ORELLANA']);
        Canton::create(['id_provincia' => 22, 'name' => 'AGUARICO']);
        Canton::create(['id_provincia' => 22, 'name' => 'LA JOYA DE LOS SACHAS']);
        Canton::create(['id_provincia' => 22, 'name' => 'LORETO']);
        Canton::create(['id_provincia' => 23, 'name' => 'SANTO DOMINGO']);
        Canton::create(['id_provincia' => 24, 'name' => 'SANTA ELENA']);
        Canton::create(['id_provincia' => 24, 'name' => 'LA LIBERTAD']);
        Canton::create(['id_provincia' => 24, 'name' => 'SALINAS']);
        Canton::create(['id_provincia' => 25, 'name' => 'LAS GOLONDRINAS']);
        Canton::create(['id_provincia' => 25, 'name' => 'MANGA DEL CURA']);
        Canton::create(['id_provincia' => 25, 'name' => 'EL PIEDRERO']);
    }
}
